# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people_app.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
