# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0004_auto_20170127_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('information', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
