# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0005_auto_20170206_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_List',
            new_name='GroupAll',
        ),
    ]
