# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0007_auto_20170207_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.AddField(
            model_name='group',
            name='information',
            field=models.TextField(default='A normal group'),
        ),
    ]
